---

- name: Configure the git user
  block:
    - ansible.builtin.command: git config --global user.name 'GitHub Actions[bot]'
    - ansible.builtin.command: git config --global user.email 'bot@noreply.github.com'

- when: secrets_init_gpg_private_key | length == 0 or secrets_init_gpg_public_key | length == 0
  module_defaults:
    ansible.builtin.command:
      chdir: "{{ secrets_cwd }}"
  block:
  - name: Generate GnuPG key
    ansible.builtin.command: gpg --batch --passphrase '' --homedir ~/.gnupg --quick-generate-key user1 default default never

  - name: Register GnuPG list keys output into a parseable format
    ansible.builtin.command: gpg --list-keys --with-colons --keyid-format=long --with-fingerprint
    register: gpg_listkeys_colonsfmt

  - name: Catch the generated GnuPG key ID
    set_fact:
      gpg_fingerprint_generatedkey: "{{ item | regex_replace('^fpr:+([^:]+):$','\\1') }}"
      gpg_fingerprint_generatedkey_found: false
    when: item.startswith('fpr') and (gpg_fingerprint_generatedkey_found | default(true))
    loop: "{{ gpg_listkeys_colonsfmt.stdout_lines }}"

  - name: Register the GnuPG key
    block:
    - ansible.builtin.command: gpg --export --armor "{{ gpg_fingerprint_generatedkey }}"
      register: gpg_public_key
    - ansible.builtin.command: gpg --export-secret-keys --armor "{{ gpg_fingerprint_generatedkey }}"
      register: gpg_private_key

  - name: Add the GnuPG key as an organization secret
    block:
    - ansible.builtin.command: gh variable set GPG_PUBLIC_KEY --org tiawl-lab --visibility all --body "{{ gpg_public_key.stdout | b64encode }}"
    - ansible.builtin.command: gh variable set GPG_PRIVATE_KEY --org tiawl-lab --visibility all --body "{{ gpg_private_key.stdout | b64encode }}"
    environment:
      GH_TOKEN: "{{ secrets_token }}"

  - name: Initialize the password-store
    ansible.builtin.command: pass init "{{ gpg_fingerprint_generatedkey }}"
    environment:
      PASSWORD_STORE_DIR: "./ansible/secrets"
  - name: Initialize git with the password-store
    ansible.builtin.command:
      cmd: pass git init
      chdir: "{{ secrets_cwd }}/ansible/secrets"
    environment:
      PASSWORD_STORE_DIR: .
  - name: Create the remote repository for the password-store
    ansible.builtin.command: gh repo create 'tiawl-lab/secrets' --public
    environment:
      GH_TOKEN: "{{ secrets_token }}"
  - name: Add the newly created remote repository to the password-store
    ansible.builtin.command:
      cmd: pass git remote add origin "https://{{ secrets_token }}@github.com/tiawl-lab/secrets.git"
      chdir: "{{ secrets_cwd }}/ansible/secrets"
    environment:
      PASSWORD_STORE_DIR: .
  - name: Modify the default branch name
    ansible.builtin.command:
      cmd: pass git branch -M main
      chdir: "{{ secrets_cwd }}/ansible/secrets"
    environment:
      PASSWORD_STORE_DIR: .
  - name: Push the password-store
    ansible.builtin.command:
      cmd: pass git push --set-upstream --all
      chdir: "{{ secrets_cwd }}/ansible/secrets"
    environment:
      PASSWORD_STORE_DIR: .
  - name: Add the password-store as a submodule of tiawl-lab/demo repository
    ansible.builtin.command: git submodule add 'https://github.com/tiawl-lab/secrets.git' "${PASSWORD_STORE_DIR}"
    environment:
      PASSWORD_STORE_DIR: "./ansible/secrets"
  - name: Stage the password-store as a submodule of tiawl-lab/demo repository
    ansible.builtin.command: git add -A
  - name: Commit the password-store as a submodule of tiawl-lab/demo repository
    ansible.builtin.command: git commit --amend -m 'init'
  - name: Push the tiawl-lab/demo repository with its new submodule
    ansible.builtin.command: git push -f

  # Keep this task at the very end of this block
  - name: Cast the GnuPG key variables into strings
    set_fact:
      secrets_init_gpg_public_key: "{{ gpg_public_key.stdout | b64encode }}"
      secrets_init_gpg_private_key: "{{ gpg_private_key.stdout | b64encode }}"

- name: Import the GnuPG key
  block:
  - ansible.builtin.command:
      cmd: gpg --import -
      stdin: "{{ secrets_init_gpg_public_key | b64decode }}"
  - ansible.builtin.command:
      cmd: gpg --import -
      stdin: "{{ secrets_init_gpg_private_key | b64decode }}"

- name: Register GnuPG list keys output into a parseable format
  ansible.builtin.command: gpg --list-keys --with-colons --keyid-format=long --with-fingerprint
  register: gpg_listkeys_colonsfmt
- name: Catch the imported GnuPG key ID
  set_fact:
    gpg_fingerprint_importedkey: "{{ item | regex_replace('^fpr:+([^:]+):$','\\1') }}"
    gpg_fingerprint_importedkey_found: false
  when: item.startswith('fpr') and (gpg_fingerprint_importedkey_found | default(true))
  loop: "{{ gpg_listkeys_colonsfmt.stdout_lines }}"
- name: Add the ultimate trust level for the imported GnuPG key
  ansible.builtin.command:
    cmd: gpg --import-ownertrust -
    stdin: "{{ gpg_fingerprint_importedkey }}:6:"

- name: Switch the password-store submodule from detached mode to the main branch
  ansible.builtin.command:
    cmd: pass git checkout main 
    chdir: "{{ secrets_cwd }}/ansible/secrets"
  environment:
    PASSWORD_STORE_DIR: .

- name: Include tests tasks
  ansible.builtin.include_tasks: tests.yml
