---

# TODO: check the GPG_PUBLIC_KEY organization secret content
# TODO: check the GPG_PRIVATE_KEY organization secret content
# TODO: check the tiawl-lab/secrets git has 2 commits
# TODO: check the tiawl-lab/secrets has 2 files .gpg-id and .gitattributes
# TODO: check the tiawl-lab/secrets/.gpg-id content with the fingerprint from the main.yml task

- block:
    - name: Check if the password-store repository was created
      ansible.builtin.command: gh repo list tiawl-lab --json 'name' --jq 'if (any(.name == "secrets") | not) then (halt_error(1)) end'
    - name: Check if the GnuPG key is an organization secret 
      block:
      - ansible.builtin.command: gh variable list --org tiawl-lab --json 'name' --jq 'if (any(.name == "GPG_PUBLIC_KEY") | not) then (halt_error(1)) end'
      - ansible.builtin.command: gh variable list --org tiawl-lab --json 'name' --jq 'if (any(.name == "GPG_PRIVATE_KEY") | not) then (halt_error(1)) end'
  environment:
    GH_TOKEN: "{{ secrets_token }}"

- name: Create temporary directories
  block:
  - ansible.builtin.tempfile:
      state: directory
    register: secrets_dir
  - ansible.builtin.tempfile:
      state: directory
    register: demo_dir

- name: Clone both repositories
  block:
  - ansible.builtin.command: git clone --filter=blob:none --depth=1 https://github.com/tiawl-lab/secrets.git "{{ secrets_dir.path }}"
  - ansible.builtin.command: git clone --filter=blob:none --depth=1 https://github.com/tiawl-lab/demo.git "{{ demo_dir.path }}"
  - ansible.builtin.command:
      cmd: git submodule update --init
      chdir: "{{ demo_dir.path }}"
  - ansible.builtin.command:
      cmd: git checkout main
      chdir: "{{ demo_dir.path }}/ansible/secrets"

- name: Register the last commits on both repositories
  block:
  - ansible.builtin.command:
      cmd: git rev-parse HEAD:ansible/secrets
      chdir: "{{ demo_dir.path }}"
    register: submodule_lastcommit
  - ansible.builtin.command:
      cmd: git rev-parse HEAD
      chdir: "{{ secrets_dir.path }}"
    register: secrets_lastcommit

- name: Compare the last commits
  ansible.builtin.fail:
    msg: "tiawl-lab/demo/ansible/secrets submodule and tiawl-lab/secrets are not synchronized"
  when: secrets_lastcommit.stdout != submodule_lastcommit.stdout
