---

# TODO: put this into a daily executed pipeline
# TODO: store the old gpg private and public keys into the password-store into a dedicated directory

- name: Register GnuPG list keys output into a parseable format
  ansible.builtin.command: gpg --list-keys --with-colons --keyid-format=long --with-fingerprint
  register: gpg_listkeys_colonsfmt

- name: Register all GnuPG keys into an array
  set_fact:
    old_gpg_keys: "{{ (old_gpg_keys | default([])) + [gpg_listkeys_colonsfmt_line | regex_replace('^fpr:+([^:]+):$','\\1')] }}"
  when: gpg_listkeys_colonsfmt_line.startswith('fpr')
  loop: "{{ gpg_listkeys_colonsfmt.stdout_lines }}"
  loop_control:
    loop_var: gpg_listkeys_colonsfmt_line

- name: Register current user of the key
  set_fact:
    gpg_keys_user: "{{ item | regex_replace('^uid:u:+[^:]+:+[^:]+:+([^:]+):+[^:]:$','\\1') }}"
    gpg_keys_user_found: false
  when: item.startswith('uid:u') and (gpg_keys_user_found | default(true))
  loop: "{{ gpg_listkeys_colonsfmt.stdout_lines }}"

- name: Generate GnuPG key
  block:
  - ansible.builtin.command: gpg --batch --passphrase '' --homedir ~/.gnupg --quick-generate-key user2 default default never
    when: gpg_keys_user == "user1"
  - ansible.builtin.command: gpg --batch --passphrase '' --homedir ~/.gnupg --quick-generate-key user1 default default never
    when: gpg_keys_user == "user2"

- name: Register GnuPG list keys output into a parseable format
  ansible.builtin.command: gpg --list-keys --with-colons --keyid-format=long --with-fingerprint
  register: gpg_listkeys_colonsfmt

- name: Catch the generated GnuPG key ID
  set_fact:
    gpg_fingerprint_generatedkey: "{{ item | regex_replace('^fpr:+([^:]+):$','\\1') }}"
    gpg_fingerprint_generatedkey_found: false
  when: item.startswith('fpr') and (gpg_fingerprint_generatedkey_found | default(true)) and ((item | regex_replace('^fpr:+([^:]+):$','\\1')) not in old_gpg_keys)
  loop: "{{ gpg_listkeys_colonsfmt.stdout_lines }}"

- name: Register the new GnuPG key
  block:
  - ansible.builtin.command: gpg --export --armor "{{ gpg_fingerprint_generatedkey }}"
    register: gpg_public_key
  - ansible.builtin.command: gpg --export-secret-keys --armor "{{ gpg_fingerprint_generatedkey }}"
    register: gpg_private_key

- name: Replace the current GnuPG key organization secrets with the new GnuPG key
  block:
  - ansible.builtin.command: gh variable set GPG_PUBLIC_KEY --org tiawl-lab --visibility all --body "{{ gpg_public_key.stdout | b64encode }}"
  - ansible.builtin.command: gh variable set GPG_PRIVATE_KEY --org tiawl-lab --visibility all --body "{{ gpg_private_key.stdout | b64encode }}"
  environment:
    GH_TOKEN: "{{ secrets_token }}"

- module_defaults:
    ansible.builtin.command:
      chdir: "{{ secrets_cwd }}/ansible/secrets"
  block:
  - name: Reencrypt the password-store with the new GnuPG key
    ansible.builtin.command: pass init "{{ gpg_fingerprint_generatedkey }}"
  - name: Push the password-store
    ansible.builtin.command: pass git push
  environment:
    PASSWORD_STORE_DIR: .

- module_defaults:
    ansible.builtin.command:
      chdir: "{{ secrets_cwd }}"
  block:
  - name: Stage the updated password-store submodule of tiawl-lab/demo repository
    ansible.builtin.command: git add -A
  - name: Commit the updated password-store submodule of tiawl-lab/demo repository
    ansible.builtin.command: git commit -m 'Update tiawl-lab/secrets submodule'
  - name: Push the tiawl-lab/demo repository with the updated password-store
    ansible.builtin.command: git push

- name: Include tests tasks
  ansible.builtin.include_tasks: tests.yml
