---

- module_defaults:
    ansible.builtin.command:
      chdir: "{{ secrets_cwd }}/ansible/secrets"
  block:
  - name: Generate a new password
    ansible.builtin.command: pass generate "{{ secrets_gen_path }}" "{{ secrets_gen_len }}"
  - name: Push the password-store
    ansible.builtin.command: pass git push
  environment:
    PASSWORD_STORE_DIR: .
- module_defaults:
    ansible.builtin.command:
      chdir: "{{ secrets_cwd }}"
  block:
  - name: Stage the updated password-store submodule of tiawl-lab/demo repository
    ansible.builtin.command: git add -A
  - name: Commit the updated password-store submodule of tiawl-lab/demo repository
    ansible.builtin.command: git commit -m 'Update tiawl-lab/secrets submodule'
  - name: Push the tiawl-lab/demo repository with the updated password-store
    ansible.builtin.command: git push

- name: Include tests tasks
  ansible.builtin.include_tasks: tests.yml
