---

# TODO: check the tiawl-lab/secrets git has 1 more commit
# TODO: check the tiawl-lab/secrets generated password has the specified length

- name: Create temporary directories
  block:
  - ansible.builtin.tempfile:
      state: directory
    register: secrets_dir
  - ansible.builtin.tempfile:
      state: directory
    register: demo_dir

- name: Clone both repositories
  block:
  - ansible.builtin.command: git clone --filter=blob:none --depth=1 https://github.com/tiawl-lab/secrets.git "{{ secrets_dir.path }}"
  - ansible.builtin.command: git clone --filter=blob:none --depth=1 https://github.com/tiawl-lab/demo.git "{{ demo_dir.path }}"
  - ansible.builtin.command:
      cmd: git submodule update --init
      chdir: "{{ demo_dir.path }}"
  - ansible.builtin.command:
      cmd: git checkout main
      chdir: "{{ demo_dir.path }}/ansible/secrets"

- name: Register the last commits on both repositories
  block:
  - ansible.builtin.command:
      cmd: git rev-parse HEAD:ansible/secrets
      chdir: "{{ demo_dir.path }}"
    register: submodule_lastcommit
  - ansible.builtin.command:
      cmd: git rev-parse HEAD
      chdir: "{{ secrets_dir.path }}"
    register: secrets_lastcommit

- name: Compare the last commits
  ansible.builtin.fail:
    msg: "tiawl-lab/demo/ansible/secrets submodule and tiawl-lab/secrets are not synchronized"
  when: secrets_lastcommit.stdout != submodule_lastcommit.stdout

- name: Check if the last generated secret was pushed
  block:
  - ansible.builtin.stat:
      path: "{{ secrets_dir.path }}/{{ secrets_gen_path }}.gpg"
    register: password_file
  - ansible.builtin.fail:
      msg: "The last generated secret was not pushed to tiawl-lab/secrets"
    when: password_file.stat.exists is undefined or not password_file.stat.exists
  - ansible.builtin.stat:
      path: "{{ demo_dir.path }}/ansible/secrets/{{ secrets_gen_path }}.gpg"
    register: password_file
  - ansible.builtin.fail:
      msg: "The last generated secret was not pushed to tiawl-lab/demo/ansible/secrets"
    when: password_file.stat.exists is undefined or not password_file.stat.exists
